---
- name: Files
  include_role:
    name: c2platform.core.files
    tasks_from: main
  vars:
    role_name: haproxy  # role_name
    common_files: "{{ haproxy_files|default([]) }}"
    common_directories: "{{ haproxy_directories|default([]) }}"
    common_acl: "{{ haproxy_acl|default([]) }}"

- name: Configure in place
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf[haproxy_install_type[ansible_os_family ]] }}"
    mode: 0644
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    validate: "{{ haproxy_validate|default(omit) }}"
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled n boot.
  service:
    name: haproxy
    state: started
    enabled: yes
