---
- include_role:
    name: c2platform.tasks
    tasks_from: cert
  when: cacerts_ca_domains is defined

- name: Configure in place
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf[haproxy_install_type[ansible_os_family ]] }}"
    mode: 0644
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    validate: "{{ haproxy_bin[haproxy_install_type[ansible_os_family]] }} -f %s -c -q"
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled n boot.
  service:
    name: haproxy
    state: started
    enabled: yes
