---
- include: "{{haproxy_install_type[ansible_os_family]}}.yml"

- name: Gather facts
  include_role:
    name: c2platform.core.facts
    tasks_from: main
  vars:
    common_facts_role_name: haproxy
  when: haproxy_facts_gather_hosts is defined

- include_tasks: certs.yml
  when: haproxy_cacerts2_certificates is defined

- include: configure.yml
