---
- name: Create account
  user:
    name: "{{ haproxy_user }}"
    comment: HAProxy Load Balancer
    system: yes

- name: Make /var/lib/haproxy
  file:
    path: "{{ haproxy_chroot }}"
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: directory
    mode: 0755

- name: Check sbin
  stat:
    path: "{{ haproxy_bin }}"
  register: haproxy

- include: install.yml
  when: not haproxy.stat.exists

- include: service.yml
- include: configure.yml
