---
- name: Fact apache_settings
  set_fact:
    apache_settings: "{{ apache_os_families_settings[ansible_os_family|lower] }}"

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install Apache
  package:
    name: "{{ apache_settings['packages'] }}"
    state: "{{ apache_packages_state }}"
    enablerepo: "{{ apache_settings['enablerepo']|default(omit) }}"

- include_tasks: certs.yml
  when: apache_cacerts2_certificates is defined

- name: Files
  include_role:
    name: c2platform.core.files
    tasks_from: main
  vars:
    role_name: tomcat # role_name
    common_files: "{{ apache_files }}"
    common_directories: "{{ apache_directories }}"
    common_acl: "{{ apache_acl }}"

- block:  # debian mods
    - name: Enable Apache mods
      file:
        src: "{{ apache_settings['server_root'] }}/mods-available/{{ item }}"
        dest: "{{ apache_settings['server_root'] }}/mods-enabled/{{ item }}"
        state: link
        mode: 0644
      with_items: "{{ apache_mods_enabled }}"
      notify: restart-apache

    - name: Disable Apache mods
      file:
        path: "{{ apache_settings['server_root'] }}/mods-enabled/{{ item }}"
        state: absent
      with_items: "{{ apache_mods_disabled }}"
      notify: restart-apache
  when: ansible_os_family == 'Debian'

- name: Ensure Apache has selected state and enabled on boot
  service:
    name: "{{ apache_settings['service'] }}"
    state: "{{ apache_state }}"
    enabled: true
