---
namespace: c2platform
name: mw
version: "0.1.11"
readme: README.md
authors:
  - Onno van der Straaten (onno@onknows.com)
license_file: LICENSE

description: C2 Platform Ansible Collection for Middleware Services

tags:
  - c2platform
  - middleware
  - apache
  - docker
  - haproxy
  - nfs
  - postgresql
  - squid
  - collection
  - linux

dependencies: {}

repository: https://github.com/c2platform/ansible-collection-mw
documentation: https://github.com/c2platform/ansible-collection-mw
homepage: https://github.com/c2platform/
issues: https://github.com/c2platform/ansible-collection-mw/issues

build_ignore: []
