
namespace: c2platform
name: mw

version: 1.0.0

authors:
- Onno van der Straaten (https://github.com/onknows)

description: C2 Platform Ansible Collection with Middleware
license_file: LICENSE
readme: README.md

tags: []

dependencies:
  c2platform.platform: ">=1.0.0"

repository: https://github.com/c2platform/ansible-collection-mw
documentation: https://github.com/c2platform/ansible-collection-mw
homepage: https://github.com/c2platform/
issues: https://github.com/c2platform/ansible-collection-mw/issues

build_ignore: []
