---
- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: true

- name: restart docker containers  # noqa command-instead-of-shell
  shell:
    cmd: "docker restart {{ item['name'] }}"
  with_items: "{{ docker_containers }}"
  loop_control:
    label: "{{ item['name'] }}"
