---
haproxy_version: 2.3.2
# haproxy_conf: /etc/haproxy/haproxy.cfg
haproxy_conf: /etc/haproxy.cfg
haproxy_make_dir: /tmp/haproxy

haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Extra global vars (see README for example usage).
haproxy_global_vars: []

haproxy_bin: /usr/local/sbin/haproxy

haproxy_packages:
  - openssl-devel
  - systemd-devel
  - "@Development Tools"

haproxy_versions:
  2.3.2:
    url: https://www.haproxy.org/download/2.3/src/haproxy-2.3.2.tar.gz
    checksum: sha256:99cb73bb791a2cd18898d0595e14fdc820a6cbd622c762f4ed83f2884d038fd5
