---
- name: "tnsnames.ora {{ role }}"
  template:
    dest: "{{ role|c2platform.platform.role_script_path }}/tnsnames.ora"
    src: oracle/tnsnames.ora.j2
    mode: 0644

- name: "Oracle scripts {{ role }}"
  template:
     dest: '{{ role|c2platform.platform.role_script_path }}/{{ script }}'
     src: "oracle/{{ script }}.j2"
     mode: 0755
  with_items:
    - scn.sh
    - exp.sh
    - drop_schema.sh
    - create_schema.sh
    - recreate_schema.sh
    #- schema_info.sh
    - impdp.sh
  loop_control:
    loop_var: script
