---
- name: Rsnapshot config files
  template:
    dest: "{{ item|c2platform.platform.role_rsnapshot_config_path(vars) }}"
    src: rsnapshot.conf.j2
    mode: 0644
  with_items: '{{ backup_roles_node }}'