---
- name: Install backup utility
  apt:
    deb: "{{ backup_utility[ansible_distribution|lower]['v'+ansible_distribution_major_version]['url'] }}"
    state: present
  when: not backup_bin.stat.exists
