---
- name: Deploy app
  block:
    - name: Properties folder
      file:
        path: "{{ app['properties_folder'] }}"
        state: directory
        mode: 0755

    - name: Java properties
      template:
        dest: "{{ app['name']|c2platform.mw.tomcat_properties_file_path(app['properties_folder']) }}"
        owner: tomcat
        group: tomcat
        src: java.properties.j2
        mode: 0644

    - name: Download war
      get_url:
        url: "{{ app['source'] }}"
        dest: "{{ tomcat_directory }}//{{ app['instance'] }}/webapps/{{ app['filename'] }}"
        validate_certs: no
  when: app.deploy
