---
- name: Verkeerde tomcat versie 9
  fail:
    msg: "Versie zou 9 moeten zijn zoals amtbu01. AWX sync werkt echter zeer onbetrouwbaar. WIP. "
  when: tomcat_version != 9

- name: Deploy Tomcat apps
  include: apps.yml
  loop: "{{ tomcat_apps }}"
  loop_control:
    label: "{{ app['name'] }}"
    loop_var: app
  when:
    - tomcat_apps is defined

- include: jmx.yml
