---
- name: Deploy Tomcat apps
  include: apps.yml
  loop: "{{ tomcat_apps }}"
  loop_control:
    label: "{{ app['name'] }}"
    loop_var: app
  when:
    - tomcat_apps is defined

- include: jmx.yml
