---
- name: Generate private key
  openssl_privatekey:
    path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}-pk.pem"
  when: reverse_proxy_vhosts[item].ssl_pk_url is not defined
  with_items: "{{ reverse_proxy_vhosts }}"
  notify: reload-apache

- name: Generate CSR
  openssl_csr:
    path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.csr"
    privatekey_path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}-pk.pem"
    common_name: "{{ reverse_proxy_vhosts[item].server_name }}"
  when: reverse_proxy_vhosts[item].ssl_cert_url is not defined
  with_items: "{{ reverse_proxy_vhosts }}"
  notify: reload-apache

- name: Generate certificate.
  openssl_certificate:
    path: "{{ reverse_proxy_etc_ssl_certs[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.pem"
    privatekey_path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}-pk.pem"
    csr_path: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.csr"
    provider: selfsigned
  when: reverse_proxy_vhosts[item].ssl_cert_url is not defined
  with_items: "{{ reverse_proxy_vhosts }}"
  notify: reload-apache

- name: Download key
  get_url:
    url: '{{ reverse_proxy_vhosts[item].ssl_pk_url }}'
    dest: "{{ reverse_proxy_etc_ssl_private[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}-pk.pem"
  when: reverse_proxy_vhosts[item].ssl_pk_url is defined
  with_items: "{{ reverse_proxy_vhosts }}"
  notify: reload-apache

- name: Download certificate
  get_url:
    url: '{{ reverse_proxy_vhosts[item].ssl_cert_url }}'
    dest: "{{ reverse_proxy_etc_ssl_certs[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}.pem"
  when: reverse_proxy_vhosts[item].ssl_cert_url is defined
  with_items: "{{ reverse_proxy_vhosts }}"
  notify: reload-apache

- name: Download bundle
  get_url:
    url: '{{ reverse_proxy_vhosts[item].ssl_bundle_url }}'
    dest: "{{ reverse_proxy_etc_ssl_certs[ansible_os_family] }}{{ reverse_proxy_vhosts[item].server_name }}-bundle.pem"
  when: reverse_proxy_vhosts[item].ssl_bundle_url is defined
  with_items: "{{ reverse_proxy_vhosts }}"
  notify: reload-apache
