---
- include: certs.yml
- include: "{{ ansible_os_family }}.yml"

- name: Copy favicon
  copy:
    dest: "{{ apache_vhosts[0].documentroot }}/favicon.ico"
    src: "{{ reverse_proxy_global_favicon }}"
    mode: 0644
  when: reverse_proxy_global_favicon is defined

- name: Environment file
  template:
    src: environment.j2
    dest: "{{ apache_vhosts[0].documentroot }}/environment"
    mode: 0644
  when: reverse_proxy_environment is defined

- include_tasks: static_files.yml
  when: reverse_proxy_static_files is defined

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true
