---
- include: proxy_for_containers.yml
  when: docker_proxy_http is defined and docker_proxy_users is defined

- name: Docker service
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    mode: 0755
  when: docker_proxy_http is defined

- name: Proxy config Docker service
  template:
    dest: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    src: http-proxy.conf.j2
    mode: 0644
  when: docker_proxy_http is defined
  notify:
    - systemctl-daemon-reload
    - restart docker